title: T1 - 2018 / 2019
logo: https://www.bordeaux-inp.fr/sites/default/files/upload/page-edito/inp/img/logos/logo.em-bxinp.jpg
description: Alexis Bagarre - Cours de Télécom. 1A
show_downloads: false
theme: jekyll-theme-minimal
